include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/kube_image_deploy.yml
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/dependency_scanning.yml
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/js_common.yml

stages: [test, build, image, deploy]

test:
  extends: .npm:test

scan:
  extends: .scan:npm

build:project:
  stage: build
  image: jitesoft/node-base
  variables:
    NODE_ENV: production
  script:
    - npm install
    - npm run build:prod
  artifacts:
    paths:
      - dist
      - Dockerfile
    when: on_success
    expire_in: 2 days
  only:
    - master

build:docker:
  variables:
    GIT_STRATEGY: none
  stage: image
  dependencies:
    - build:project
  image: docker:latest
  script:
    - sed -i -e "s/.js/.js?v=${CI_COMMIT_SHA}/g" dist/index.html
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  only:
    - master

deploy:
  extends: .k8s_deploy
  stage: deploy
  variables:
    KUBE_DEPLOY_NAMESPACE: jitesoft
    KUBE_DEPLOY_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    GIT_STRATEGY: none
    KUBE_DEPLOY_CONTAINER: web
    KUBE_DEPLOY_DEPLOYMENT: jitesoft-dep
  only:
    - master
  environment:
    name: production
    url: https://jitesoft.com
